export const defaultWebsiteSettings = {
  siteTitle: 'PenPOS',
  siteDescription: 'Restoran, cafe, magaza ve marketler icin ayri akisli modern bulut otomasyon sistemi.',
  brandSubtitle: 'Restoran - Magaza - Market',
  headerSystemsLabel: 'Sistemler',
  headerFeaturesLabel: 'Ozellikler',
  headerPricingLabel: 'Fiyat',
  headerTrainingLabel: 'Egitim Videolari',
  heroTitle: 'Restoran ve magaza sistemlerini ayri ayri yonetin.',
  heroSubtitle: 'YENI NESIL SATIS VE ADISYON YONETIMI',
  heroPointOne: 'QR menu dahil',
  heroPointTwo: 'Sinirsiz sube',
  heroPointThree: 'YouTube egitim videolari',
  heroDescription: 'PenPOS; restoran-cafe ve magaza-market icin ayri girisleri, ayri ekran akislarÄ± olan modern otomasyon yapisidir. Restoran tarafinda QR menu standart olarak dahildir; her isletme istedigi kadar sube acabilir.',
  trialDays: 7,
  primaryCtaText: '1 Haftalik Ucretsiz Deneme',
  primaryCtaUrl: '/register',
  secondaryCtaText: 'Giris Yap',
  secondaryCtaUrl: '/login',
  restaurantLoginText: 'Restoran Girisi',
  restaurantLoginUrl: '/login/restoran',
  canteenLoginText: 'Kantin Girisi',
  canteenLoginUrl: '/canteen/login',
  platformLoginText: 'Platform Girisi',
  platformLoginUrl: '/platform/login',
  marketLoginUrl: '/canteen/login',
  registerUrl: '/register',
  androidButtonText: 'Android Uygulamasini Indir',
  androidApkUrl: 'https://drive.google.com/uc?id=1_QZs8wYc0mtVSfPtBllJIXt5r-e9M9iv&export=download',
  androidButtonActive: true,
  systemsSectionEyebrow: 'PenPOS Yapisi',
  systemsSectionTitle: 'Restoran ve magaza ayni cati altinda, ayri sistem mantiginda.',
  systemsSectionText: 'Her sistem kendi girisine ve ekran akisina sahip olur. Firma isterse restoran, isterse magaza/market yapisiyla ilerler.',
  operationsSectionEyebrow: 'Canli Isletme Yonetimi',
  operationsSectionTitle: 'Tum operasyonlari tek panelden kontrol edin.',
  operationsSectionText: 'Mutfak hazirligindan kurye akisina, cari hesaplardan canli raporlara kadar tum isletme surecleri PenPOS icinde birlesir.',
  pricingSectionEyebrow: 'Fiyatlandirma',
  pricingSectionTitle: '1 haftalik ucretsiz deneme ile baslayin.',
  pricingSectionText: 'Demo talep etmek yerine kullanici dogrudan deneyebilir; giris yap alani mevcut uyeler icin acik kalir.',
  trainingSectionEyebrow: 'Egitim Videolari',
  trainingSectionTitle: 'Sistemi kisa videolarla hizli ogrenin.',
  trainingSectionText: 'Kurulum, satis, cari hesap, QR menu ve raporlama akislarini mevcut egitim videolariyla adim adim izleyebilirsiniz.',
  contactSectionTitle: 'Iletisim',
  whatsappLabel: 'WhatsApp Hatti',
  whatsappStatusText: 'Cevrimici',
  whatsappUrl: '',
  phone: '',
  email: '',
  address: '',
  footerText: '© 2026 PenPOS. Restoran, magaza ve market otomasyon sistemi.',
  themeBackgroundStart: '#1c1714',
  themeBackgroundEnd: '#000000',
  themeHeaderBackground: '#080706',
  themeSurfaceColor: '#11100f',
  themeAccentColor: '#b8734b',
  themeAccentTextColor: '#ffffff',
  themeTextColor: '#ffffff',
  themeMutedTextColor: '#b7ada6',
  themeBorderColor: '#6e625a',
  themeFooterBackground: '#000000',
  socialInstagramUrl: '',
  socialFacebookUrl: '',
  socialXUrl: '',
  socialYoutubeUrl: '',
  socialLinkedinUrl: '',
  features: [
    { id: 'feature-1', icon: 'store', title: 'Restoran / Cafe', text: 'Masa, adisyon, mutfak, paket servis, kurye ve QR menu akislari restoran tarafinda birlikte calisir.', sortOrder: 1, active: true },
    { id: 'feature-2', icon: 'cart', title: 'Magaza / Market', text: 'Barkodlu hizli satis, urun fiyat listesi, stok ve online satis mantigi magazaya uyarlanir.', sortOrder: 2, active: true },
    { id: 'feature-3', icon: 'chart', title: 'Canli Raporlar', text: 'Z raporu, odeme tipleri, sube filtreleri ve cari bakiye gibi veriler tek panelde izlenir.', sortOrder: 3, active: true }
  ],
  systemCards: [],
  pricingPlans: [
    { id: 'plan-1', name: 'Baslangic', price: 'Ozel', period: '', description: 'Isletmenize, sube sayiniza ve kullanim yogunlugunuza gore ozellestirilir.', items: ['QR menu dahil', 'Sinirsiz sube mantigi', 'Canli raporlar'], popular: false, buttonText: '1 Haftalik Ucretsiz Deneme', buttonUrl: '/register', active: true, sortOrder: 1 },
    { id: 'plan-2', name: 'Restoran + Magaza', price: 'Ozel', period: '', description: 'Ayni firmada restoran ve magaza akislarini birlikte yonetmek isteyen yapilar icin uygun kurulum.', items: ['Restoran ve magaza ayri akis', 'Egitim videolari', 'Sube bazli yonetim'], popular: true, buttonText: '1 Haftalik Ucretsiz Deneme', buttonUrl: '/register', active: true, sortOrder: 2 }
  ],
  trainingVideos: [
    { id: 'video-1', title: 'Uyelik ve Ilk Kurulum', description: 'Ilk hesap acilisi ve panel tanitimi.', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', category: 'general', active: true, sortOrder: 1 },
    { id: 'video-2', title: 'Restoran Satis Akisi', description: 'Masa ve adisyon akisinin temel kullanimi.', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', category: 'restaurant', active: true, sortOrder: 2 },
    { id: 'video-3', title: 'Kantin Barkodlu Satis', description: 'Hizli kasa ve barkodlu satis ornegi.', youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', category: 'market', active: true, sortOrder: 3 }
  ],
  integrations: [],
  seoTitle: 'PenPOS | Restoran ve Kantin Otomasyonu',
  seoDescription: 'PenPOS ile restoran/cafe ve kantin/market akislarÄ± ayri girislerle yonetilir. QR menu dahil, sinirsiz sube ve raporlama hazir.',
  seoKeywords: 'penpos,pos,restoran otomasyonu,kantin otomasyonu,market otomasyonu,qr menu',
  isPublished: true,
  updatedAt: null
}

export const heroBadges = ['1 Hafta Ucretsiz', 'Kredi Kartsiz Basla', 'Ayri Restoran ve Kantin Girisi', 'QR Menu Dahil', 'Sinirsiz Sube', 'Raporlama']
export const reportItems = ['Gunluk ciro', 'Saatlik satis yogunlugu', 'En cok satan urunler', 'Kategori karliligi', 'Garson performansi', 'Paket servis durumu', 'Odeme tipi analizi', 'Sube karsilastirmasi']
